[package]
name = "html5gum-fuzz"
version = "0.1.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
html5gum = { path = "../" }
html5gum_old = { version = "0.3.0", package = "html5gum" }
afl = "0.11.0"
html5ever = "0.25.1"
pretty_assertions = "1.0.0"


# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[lib]
name = "testcase"
path = "src/testcase.rs"

[[bin]]
name = "main_libfuzzer"
path = "fuzz_targets/main_libfuzzer.rs"
test = false
doc = false

[[bin]]
name = "main_afl"
path = "src/main_afl.rs"
test = false
doc = false

[[bin]]
name = "main_cli"
path = "src/main_cli.rs"
test = false
doc = false
